### ISSUE TITLE
Handy Answer Keys Enable 'c' option

### ISSUE THREAD

**Issue by ChocoTonic** [ijgnd/anki__jkl_answer_keys_configurable#1]
[right hand reviews / hjkl answer shortcuts / Handy Answer Keys (configurable)](https://ankiweb.net/shared/info/850294128)

> c) ... you can configure if the meaning of the "2" and "3" key should be adjusted depending on the number of buttons you see. This will be less important once the V2 scheduler is no longer experimental but the default. Then you'll also have 4 buttons for new and learning cards, see this document and this source code on github. This is disabled by default.

could you upload some documentation or a guide on how to change the third key "l" or "3" 'easy' for learning cards but 'good' for cards in review?

addon in feature discussed:
[Handy Answer Keys Shortcuts Amended](https://ankiweb.net/shared/info/1848421740)

>  Bind 'j', 'k', 'l', ';', 'รถ' to card answering actions.  This allows answering with
>  right hand, keeping your thumb on SPC (default action) and other fingers on
>  'j', 'k', 'l', ';'. If the number of buttons is less than 4, 'l' and ';' will
>  do the right thing - choose the maximal ease level.

**Comment by ijgnd** [comment]
You can configure this add-on in the usual way for 2.1: Go to "Tools-Add-ons" (from the menu bar of the main window). In the window that opens select the name of my add-on in the list on the left, then click the button "Config" on the right side.

Does this solve your problem?

**Comment by ChocoTonic** [comment]
> Does this solve your problem?

thank you, it did!

I didn't realize it was there in the Config Menu
